### PR TITLE
Add bright/dark theme logo support

### PR DESCRIPTION
**Pull request by alvaromartmart**
- Added bright version of Nextflow logo with "flow" in white
- Updated README to show dark/bright version depending on current user theme for better readability

### CODE REVIEW

**Review by pditommaso — APPROVED** [review]
Nice 👍

**Comment by pditommaso** [comment]
An now is broken! 😆 

Screenshot 2022-06-01 at 10 29 11

**Comment by ewels** [comment]
I think it probably needs the fully qualified URL instead of the relative link.. Looking at the previous version / docs example / other repos they use a full URL.

**Comment by ewels** [comment]
Fix 👉🏻  https://github.com/nextflow-io/trademark/pull/2

**Comment by alvaromartmart** [comment]
> I think it probably needs the fully qualified URL instead of the relative link.. Looking at the previous version / docs example / other repos they use a full URL.

Aahh that may be the reason. It previews OK for me, but maybe because I'm on a local env
Screenshot 2022-06-01 at 10 38 08

**Comment by ewels** [comment]
Snap! 😉

**Pull request merged**
